# Generated by Django 2.2.5 on 2019-10-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='natureValue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nature_value', to='biapi.NatureValue'),
        ),
    ]
