# Generated by Django 2.2.5 on 2019-10-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biapi', '0002_auto_20191027_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Max'),
        ),
        migrations.AddField(
            model_name='value',
            name='min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Min'),
        ),
    ]
