# Generated by Django 2.2.5 on 2019-10-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biapi', '0003_auto_20191028_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Value'),
        ),
    ]
