# Generated by Django 2.2.5 on 2019-10-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biapi', '0005_auto_20191029_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='units',
        ),
        migrations.AddField(
            model_name='value',
            name='mass',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mass'),
        ),
    ]
