# Generated by Django 2.2.5 on 2019-10-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biapi', '0007_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
