# Generated by Django 2.2.6 on 2019-11-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biapi', '0008_demand_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='forcast',
            field=models.BooleanField(blank=True, null=True, verbose_name='Forcast'),
        ),
    ]
